
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbjwapqjvldgmyrmlklu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiandhcHFqdmxkZ215cm1sa2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODEyNTcsImV4cCI6MjA1NzU1NzI1N30.sJxxVPfW-iAocMtDB74-QX4iNStVT245deIPdVyPsvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
